#include <stdio.h>
#include <stdlib.h>
#include <inttypes.h>

#define MIN(a,b) ((a) < (b) ? (a) : (b))

#ifndef N
#	define N    5000000
#endif

#define REPS 500 // high enough to minimize branch misses, low enough to fit 256 * REPS * (3/8) + 8192 in cache

extern uint32_t get_random(uint32_t prev[64], int n, uint32_t *out, uint32_t multiplier, uint32_t mask);
extern uint32_t compare_low_16(uint32_t *a, uint32_t *b, uint32_t n);

int main(void)
{
	uint32_t a[64] = { 65 }, b[64] = { 8921 };
	char line[1000];

	static uint32_t a_out[64 * REPS], b_out[64  * REPS];
	uint32_t nCompared = 0, nEqual = 0, b_size = 0, b_pos = 0;

	FILE *f = fopen("input", "r");
	if (!f) {
		fprintf(stderr, "Could not open 'input'. Using default values 65 and 8921.\n");
	} else {
		fgets(line, 100, f); a[0] = strtol(line + 24, NULL, 10);
		fgets(line, 100, f); b[0] = strtol(line + 24, NULL, 10);
		fclose(f);
	}

	// calculate the first 64 numbers scalarly
	for (int i=1; i<64; i++) {
		a[i] = (a[i-1] * 16807LU) % 0x7FFFFFFF;
		b[i] = (b[i-1] * 48271LU) % 0x7FFFFFFF;
	}

	while (nCompared < N) {
		// generate REPS * 64 random numbers, mask them with & 0x3, store the multiples-of-4 in a_out[]
		uint32_t a_pos = 0;
		uint32_t a_size = get_random(a, REPS, a_out, 0x28d61248 /* 16807^64 */, 0x3);

		// be sure not to overshoot N
		if (a_size > N - nCompared) a_size = N - nCompared;

		nCompared += a_size;

		// for each A number found: compare to a number generated by B.
		while (a_pos != a_size) {
			// b_out buffer empty: generate more
			while (b_pos == b_size) {
				b_pos = 0;
				b_size = get_random(b, REPS, b_out, 0x2adc4dff /* 48271^64 */, 0x7);
			}

			int take = MIN(a_size-a_pos, b_size-b_pos);
			nEqual += compare_low_16(a_out + a_pos, b_out + b_pos, take);

			a_pos += take;
			b_pos += take;
		}
	}

	printf("Part 2: %" PRIu32 "\n", nEqual);
}
